--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 16/9/2018 18:05:40
-- Server version: 5.5.5-10.1.34-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE constructora;

--
-- Drop table `herramienta`
--
DROP TABLE IF EXISTS herramienta;

--
-- Drop table `material`
--
DROP TABLE IF EXISTS material;

--
-- Drop table `recibo`
--
DROP TABLE IF EXISTS recibo;

--
-- Drop table `cotizacion`
--
DROP TABLE IF EXISTS cotizacion;

--
-- Drop table `cliente`
--
DROP TABLE IF EXISTS cliente;

--
-- Drop table `inventario`
--
DROP TABLE IF EXISTS inventario;

--
-- Drop table `obreros`
--
DROP TABLE IF EXISTS obreros;

--
-- Set default database
--
USE constructora;

--
-- Create table `obreros`
--
CREATE TABLE obreros (
  `Cod Obrero` int(11) NOT NULL AUTO_INCREMENT,
  CI int(11) DEFAULT NULL,
  `Nombre Completo` varchar(255) DEFAULT NULL,
  `Fecha de Nacimiento` char(20) DEFAULT NULL,
  `Numero de Telefono` int(11) DEFAULT NULL,
  PRIMARY KEY (`Cod Obrero`)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_unicode_520_ci;

--
-- Create table `inventario`
--
CREATE TABLE inventario (
  `Cod Inventario` int(11) NOT NULL,
  `Cod Herramientas` int(11) DEFAULT NULL,
  `Cod Materiales` int(11) DEFAULT NULL,
  `Cod Obrero` int(11) NOT NULL,
  `Fecha Ultima revision` char(20) DEFAULT NULL,
  PRIMARY KEY (`Cod Inventario`)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_unicode_520_ci;

--
-- Create foreign key
--
ALTER TABLE inventario
ADD CONSTRAINT `FK_inventario_obreros_Cod Obrero` FOREIGN KEY (`Cod Obrero`)
REFERENCES obreros (`Cod Obrero`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `cliente`
--
CREATE TABLE cliente (
  CodCliente int(11) NOT NULL AUTO_INCREMENT,
  `C.I` int(11) DEFAULT NULL,
  `Nombre Completo` varchar(255) DEFAULT NULL,
  PRIMARY KEY (CodCliente)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_unicode_520_ci;

--
-- Create table `cotizacion`
--
CREATE TABLE cotizacion (
  `Numero Cotizacion` int(11) NOT NULL AUTO_INCREMENT,
  `Cod Cliente` int(11) NOT NULL,
  `Cod Obrero` int(11) NOT NULL,
  `Cod Materiales` int(11) NOT NULL,
  Fecha char(20) DEFAULT NULL,
  PRIMARY KEY (`Numero Cotizacion`)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_unicode_520_ci;

--
-- Create foreign key
--
ALTER TABLE cotizacion
ADD CONSTRAINT FK_cotizacion_cliente_CodCliente FOREIGN KEY (`Cod Cliente`)
REFERENCES cliente (CodCliente) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE cotizacion
ADD CONSTRAINT `FK_cotizacion_obreros_Cod Obrero` FOREIGN KEY (`Cod Obrero`)
REFERENCES obreros (`Cod Obrero`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `recibo`
--
CREATE TABLE recibo (
  `Numero Compra` int(11) NOT NULL AUTO_INCREMENT,
  `Numero Cotizacion` int(11) NOT NULL,
  `Cod Cliente` int(11) DEFAULT NULL,
  Fecha char(20) DEFAULT NULL,
  Precio decimal(10, 0) DEFAULT NULL,
  PRIMARY KEY (`Numero Compra`, `Numero Cotizacion`)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_unicode_520_ci;

--
-- Create foreign key
--
ALTER TABLE recibo
ADD CONSTRAINT FK_recibo_cliente_CodCliente FOREIGN KEY (`Cod Cliente`)
REFERENCES cliente (CodCliente) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE recibo
ADD CONSTRAINT `FK_recibo_cotizacion_Numero Cotizacion` FOREIGN KEY (`Numero Cotizacion`)
REFERENCES cotizacion (`Numero Cotizacion`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `material`
--
CREATE TABLE material (
  `Cod Material` int(11) NOT NULL AUTO_INCREMENT,
  `Cod Inventario` int(11) NOT NULL,
  Cantidad decimal(10, 0) DEFAULT NULL,
  Dimensiones decimal(10, 0) DEFAULT NULL,
  Precio decimal(10, 0) DEFAULT NULL,
  `Lugar de Origen` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`Cod Material`)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_unicode_520_ci;

--
-- Create foreign key
--
ALTER TABLE material
ADD CONSTRAINT `FK_material_inventario_Cod Inventario` FOREIGN KEY (`Cod Inventario`)
REFERENCES inventario (`Cod Inventario`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE inventario
ADD CONSTRAINT `FK_inventario_material_Cod Material` FOREIGN KEY (`Cod Materiales`)
REFERENCES material (`Cod Material`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `herramienta`
--
CREATE TABLE herramienta (
  `Cod Herramienta` int(11) NOT NULL AUTO_INCREMENT,
  `Cod Inventario` int(11) NOT NULL,
  `Fecha Adquisicion` char(20) DEFAULT NULL,
  Precio decimal(10, 0) DEFAULT NULL,
  Especificacion varchar(255) DEFAULT NULL,
  `Lugar de Origen` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`Cod Herramienta`)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_unicode_520_ci;

--
-- Create foreign key
--
ALTER TABLE herramienta
ADD CONSTRAINT `FK_herramienta_inventario_Cod Inventario` FOREIGN KEY (`Cod Inventario`)
REFERENCES inventario (`Cod Inventario`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE inventario
ADD CONSTRAINT `FK_inventario_herramienta_Cod Herramienta` FOREIGN KEY (`Cod Herramientas`)
REFERENCES herramienta (`Cod Herramienta`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- 
-- Dumping data for table obreros
--
-- Table constructora.obreros does not contain any data (it is empty)

-- 
-- Dumping data for table cliente
--
-- Table constructora.cliente does not contain any data (it is empty)

-- 
-- Dumping data for table cotizacion
--
-- Table constructora.cotizacion does not contain any data (it is empty)

-- 
-- Dumping data for table recibo
--
-- Table constructora.recibo does not contain any data (it is empty)

-- 
-- Dumping data for table material
--
-- Table constructora.material does not contain any data (it is empty)

-- 
-- Dumping data for table inventario
--
-- Table constructora.inventario does not contain any data (it is empty)

-- 
-- Dumping data for table herramienta
--
-- Table constructora.herramienta does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;