--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 18/9/2018 01:19:07
-- Server version: 5.5.5-10.1.34-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE constructora;

--
-- Drop table `inventario`
--
DROP TABLE IF EXISTS inventario;

--
-- Drop table `herramienta`
--
DROP TABLE IF EXISTS herramienta;

--
-- Drop table `material`
--
DROP TABLE IF EXISTS material;

--
-- Drop table `recibo`
--
DROP TABLE IF EXISTS recibo;

--
-- Drop table `cotizacion`
--
DROP TABLE IF EXISTS cotizacion;

--
-- Drop table `cliente`
--
DROP TABLE IF EXISTS cliente;

--
-- Drop table `obreros`
--
DROP TABLE IF EXISTS obreros;

--
-- Set default database
--
USE constructora;

--
-- Create table `obreros`
--
CREATE TABLE obreros (
  `Cod Obrero` int(11) NOT NULL AUTO_INCREMENT,
  CI int(11) DEFAULT NULL,
  `Nombre CompletoO` varchar(255) DEFAULT NULL,
  `Fecha de Nacimiento` char(20) DEFAULT NULL,
  `Numero de Telefono` int(11) DEFAULT NULL,
  PRIMARY KEY (`Cod Obrero`)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8,
COLLATE utf8_unicode_520_ci;

--
-- Create table `cliente`
--
CREATE TABLE cliente (
  CodCliente int(11) NOT NULL AUTO_INCREMENT,
  `C.I` int(11) DEFAULT NULL,
  `Nombre Completo` varchar(255) DEFAULT NULL,
  PRIMARY KEY (CodCliente)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8,
COLLATE utf8_unicode_520_ci;

--
-- Create table `cotizacion`
--
CREATE TABLE cotizacion (
  `Numero Cotizacion` int(11) NOT NULL AUTO_INCREMENT,
  `Cod Cliente` int(11) NOT NULL,
  `Cod Obrero` int(11) NOT NULL,
  `Cod Materiales` int(11) NOT NULL,
  Fecha char(20) DEFAULT NULL,
  PRIMARY KEY (`Numero Cotizacion`)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8,
COLLATE utf8_unicode_520_ci;

--
-- Create foreign key
--
ALTER TABLE cotizacion
ADD CONSTRAINT FK_cotizacion_cliente_CodCliente FOREIGN KEY (`Cod Cliente`)
REFERENCES cliente (CodCliente) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE cotizacion
ADD CONSTRAINT `FK_cotizacion_obreros_Cod Obrero` FOREIGN KEY (`Cod Obrero`)
REFERENCES obreros (`Cod Obrero`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `recibo`
--
CREATE TABLE recibo (
  `Numero Compra` int(11) NOT NULL AUTO_INCREMENT,
  `Numero Cotizacion` int(11) NOT NULL,
  `Cod Cliente` int(11) DEFAULT NULL,
  Fecha char(20) DEFAULT NULL,
  Precio decimal(10, 0) DEFAULT NULL,
  PRIMARY KEY (`Numero Compra`, `Numero Cotizacion`)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_unicode_520_ci;

--
-- Create foreign key
--
ALTER TABLE recibo
ADD CONSTRAINT FK_recibo_cliente_CodCliente FOREIGN KEY (`Cod Cliente`)
REFERENCES cliente (CodCliente) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE recibo
ADD CONSTRAINT `FK_recibo_cotizacion_Numero Cotizacion` FOREIGN KEY (`Numero Cotizacion`)
REFERENCES cotizacion (`Numero Cotizacion`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `material`
--
CREATE TABLE material (
  `Cod Material` int(11) NOT NULL AUTO_INCREMENT,
  `Cod Inventario` int(11) NOT NULL,
  Nombre varchar(255) NOT NULL,
  Cantidad decimal(10, 0) DEFAULT NULL,
  Precio decimal(10, 0) DEFAULT NULL,
  Dimensiones varchar(255) DEFAULT NULL,
  `Lugar de Origen` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`Cod Material`)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_unicode_520_ci;

--
-- Create index `FK_material_inventario_Cod Inventario` on table `material`
--
ALTER TABLE material
ADD INDEX `FK_material_inventario_Cod Inventario` (`Cod Inventario`);

--
-- Create table `herramienta`
--
CREATE TABLE herramienta (
  `Cod Herramienta` int(11) NOT NULL AUTO_INCREMENT,
  `Cod Inventario` int(11) NOT NULL,
  NombreH varchar(255) NOT NULL,
  `Fecha Adquisicion` char(20) DEFAULT NULL,
  Precio decimal(10, 0) DEFAULT NULL,
  Especificacion varchar(255) DEFAULT NULL,
  `Lugar de Origen` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`Cod Herramienta`)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_unicode_520_ci;

--
-- Create index `FK_herramienta_inventario_Cod Inventario` on table `herramienta`
--
ALTER TABLE herramienta
ADD INDEX `FK_herramienta_inventario_Cod Inventario` (`Cod Inventario`);

--
-- Create table `inventario`
--
CREATE TABLE inventario (
  `Cod Inventario` int(11) NOT NULL,
  `Cod Herramientas` int(11) DEFAULT NULL,
  `Cod Material` int(11) DEFAULT NULL,
  `Fecha Ultima revision` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`Cod Inventario`)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_unicode_520_ci;

--
-- Create foreign key
--
ALTER TABLE inventario
ADD CONSTRAINT `FK_inventario_herramienta_Cod Herramienta` FOREIGN KEY (`Cod Herramientas`)
REFERENCES herramienta (`Cod Herramienta`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE inventario
ADD CONSTRAINT `FK_inventario_material_Cod Material` FOREIGN KEY (`Cod Material`)
REFERENCES material (`Cod Material`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- 
-- Dumping data for table obreros
--
INSERT INTO obreros VALUES
(1, 8670226, 'Josue Cardozo', '25/10/99', 72234344);

-- 
-- Dumping data for table cliente
--
INSERT INTO cliente VALUES
(1, 8736268, 'Andres Gamboa'),
(2, 8736222, 'Felipe Castillo'),
(3, 1231244, 'Felipe Catilo'),
(4, 213455, 'Mateo lopez'),
(5, 2321342, 'Froilan Josue Cardozo');

-- 
-- Dumping data for table cotizacion
--
INSERT INTO cotizacion VALUES
(1, 1, 1, 1, '18/09/18');

-- 
-- Dumping data for table material
--
INSERT INTO material VALUES
(1, 1, 'Perfil C', 4, 18, '5', 'China'),
(2, 1, 'Yeso', 12, 10, '10 cm', 'Japon'),
(4, 1, 'Arcilla', 12, 50, '20 m', 'Japon');

-- 
-- Dumping data for table herramienta
--
INSERT INTO herramienta VALUES
(1, 1, 'Martillo Punta', '17/06/2017', 11, 'Martillo en punta', 'China'),
(2, 1, 'Martillo X ', '15/02/99', 20, 'Martillo en X', 'Japon'),
(3, 1, 'Martillo X Caro', '15/02/99', 30, 'Martillo en X', 'Italia'),
(4, 1, 'Destornillador', '13/02/17', 10, 'Destornillador Plano', 'China');

-- 
-- Dumping data for table recibo
--
-- Table constructora.recibo does not contain any data (it is empty)

-- 
-- Dumping data for table inventario
--
INSERT INTO inventario VALUES
(1, 1, 1, '18/09/18');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;